### PR TITLE
unbreak personvideos

### PR DESCRIPTION
**Pull request by sevenrats**
I broke personvideos when I changed the slider logic.
My changes (start all the tasks at once instead of having the task handlers call the next task in sequence) makes the load time substantially faster in my tests, ~~but it has the (obvious) side effect of putting the exrasrows in whatever order the tasks return.
this is a draft while I try to think of a solution that gives us the loading speed and the deterministic order.~~

### CODE REVIEW

**Comment by sevenrats** [comment]
- [x] personvideos come up in random order
- [x] tv show highlight rectangle is wrong shape in personvideos

**Comment by sevenrats** [comment]
slows down the loading of "Cast and Crew" info a little bit on my raspberry pi, but imho this is better.

**Comment by sevenrats** [comment]
actually i think i may be able to retool this logic to make it faster.

**Comment by candry7731** [comment]
I get errors when trying to pull up a cast extra's slider
https://user-images.githubusercontent.com/83685828/217431125-6df157e1-8e61-41f6-9622-9b8c7a5ec217.mp4

image

**Comment by candry7731** [comment]
Man, this is a beautiful pr!

**Pull request merged**
